spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.108:3306/mimidai_20170316?characterEncoding=utf-8
    username: root
    password: Mimidai123
    maxActive: 10
    maxIdle: 5
    minIdle: 0
    initialSize: 0
    filters: stat,wall,log4j
  redis:
    host: 192.168.1.108
    port: 6379
    password:
    pool:
      max-active: 800
      max-idle: 200
      min-idle: 20
      max-wait: 10000

#--------------------------------

slave:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.108:3306/mimidai_20170316?characterEncoding=utf-8
    username: root
    password: Mimidai123



#--------------------------------

logging: 
   file: D:/logs/mimidai-cms.log
   level: info
#--------------------------------
switch:
   isSendPush: false
   isSendMessage: false